### ISSUE TITLE
在ios文件夹下面执行 pod install

### ISSUE THREAD

**Issue by steele-cjf** [lighthx/react-native-card-ocr#2]
在ios文件夹下面执行 pod install?? Podfile都没有，怎么装

**Comment by lighthx** [comment]
额，rn60以上不是自带pod么？

**Comment by steele-cjf** [comment]
这个项目的ios目录下Podfile文件都没有，怎么进行pod install？

**Comment by steele-cjf** [comment]
第二个package.json文件，执行命令也没有啊，只有一个test；这个项目md介绍的 本地的启动步骤 完全不对啊

**Comment by lighthx** [comment]
应该所有的RN原生桥接module 都是这么操作，npm到现有的rn项目中，如果你的项目rn的版本>0.6*就去 项目根目录/ios 文件夹下 执行 pod install， 如果不是就执行下面的 就用老的link方式，有什么问题？

**Comment by steele-cjf** [comment]
也就是说当前这个项目只支持第三方sdk集成，不支持直接运行

**Comment by lighthx** [comment]
是的，本身是为了快速集成到现有的项目中，你提的这些问题最好看看RN的文档， 这条issue会关闭
